### ISSUE TITLE
Adding Github Links

### ISSUE THREAD

**Issue by eneskemalergin** [NAU-ACM/ACM-Showcase#1]
Hey @BedirT 
I guess it would be better to have github links for members in the lab pages. I don't know how exactly you can do that but it should have that option defined in the theme, something like this;

```
<i class="icon social_github"></i>
```

Also I propose to change the Facebook option into Twitter one, some members may not have Facebook....

**Comment by BedirT** [comment]
Yes we will add them, Burak will upload it to icon pack. We are waiting for it, so we will have 3 icons under each member @eneskemalergin . Other one ... Some may have facebook , some may have twitter :) So if you want to change the icon , you can. Also if anyone wants to add other social platforms You are more then welcome. Just change the "facebook" part with "twitter"
